### ISSUE TITLE
Getting this error. Please help me

### ISSUE THREAD

**Issue by johna3212** [lavalibs/lavalink.js#26]
```[ioredis] Unhandled error event: ParserError: Protocol error, got "H" as reply type byte. Please report this.
    at handleError (C:\Users\username\Desktop\a\node_modules\redis-parser\lib\parser.js:190:15)
    at parseType (C:\Users\username\Desktop\a\node_modules\redis-parser\lib\parser.js:304:14)
[ioredis] Unhandled error event: ParserError: Protocol error, got "H" as reply type byte. Please report this.
    at handleError (C:\Users\username\Desktop\a\node_modules\redis-parser\lib\parser.js:190:15)
    at parseType (C:\Users\username\Desktop\a\node_modules\redis-parser\lib\parser.js:304:14)
events.js:298
      throw er; // Unhandled 'error' event
      ^

Error: write EPROTO 14140:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:c:\ws\deps\openssl\openssl\ssl\record\ssl3_record.c:332:

    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:92:16)
Emitted 'error' event on LavaqueueNode instance at:
    at WebSocket.error (C:\Users\username\Desktop\a\node_modules\lavalink\dist\src\core\Connection.js:39:27)
    at WebSocket.emit (events.js:321:20)
    at WebSocket.EventEmitter.emit (domain.js:485:12)
    at ClientRequest.<anonymous> (C:\Users\username\Desktop\a\node_modules\lavalink\node_modules\ws\lib\websocket.js:568:15)
    at ClientRequest.emit (events.js:321:20)
    at ClientRequest.EventEmitter.emit (domain.js:485:12)
    at TLSSocket.socketErrorListener (_http_client.js:424:9)
    at TLSSocket.emit (events.js:321:20)
    at TLSSocket.EventEmitter.emit (domain.js:485:12)
    at errorOrDestroy (internal/streams/destroy.js:128:12) {
  errno: -4046,
  code: 'EPROTO',
  syscall: 'write'
}```

**Comment by appellation** [comment]
Looks like an error was emitted by your websocket connection related to SSL certificates. I would recommend ensuring that your lavalink instance has a valid SSL certificate or no SSL certificate and change the protocol accordingly.

Either way, this doesn't appear to be an issue with lavalink.js itself.
